# Trigger to the branches
trigger:
  branches:
    include:
    - develop

# Trigger pipeline check if a PR is created against the branches
pr:
  branches:
    include:
    - develop

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  isDevBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  artifactName: $[ if(variables['isDevBranch']) { 'bid-portal-demo-artifact-dev' } else { 'bid-portal-demo-artifact' } ]

steps:
# Use Node version 18.x
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Use Node.js $(nodeVersion)'

# Use pnpm (much faster)
- script: |
    npm install -g pnpm
  displayName: 'Install pnpm'

# Install the packages
- script: |
    pnpm install
  displayName: 'Install project packages'

# Pre-build checks: lint, test
- script: |
    pnpm lint
  displayName: 'Pre-build checks: lint, test'

# Build the project
- script: |
    pnpm build
  displayName: 'Build project'

# Publish the build artifact
- task: PublishBuildArtifacts@1
  inputs:
    # dist folder only. We don't need the rest of the files
    pathtoPublish: 'dist'
    artifactName: ${artifactName}
    publishLocation: 'Container'
  # Exclude PRs from creating an artifact
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['isDevBranch'], true))
