# Trigger pipeline from branches
trigger:
  branches:
    include:
    - develop

# Trigger pipeline from PRs. Currently, has to be configured in Azure DevOps settings for it to fully work
pr:
  autoCancel: true
  branches:
    include:
      - develop

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

# nodeVersion: '18.x'
# isDevBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

variables:
  nodeVersion: '18.x'
  isDevBranch: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['System.PullRequest.TargetBranch'], 'develop'))]

stages:
  - stage: DevBranchStage
    displayName: 'Stage for Dev Branch'
    condition: eq(variables.isDevBranch, true)
    variables:
      - group: bid-portal-demo-dev
    jobs:
      - job: Job1
        steps:
          - template: common-steps-azure-pipeline.yml
