steps:
# Use Node version 18.x
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Use Node.js $(nodeVersion)'

# Use pnpm (much faster)
- script: |
    npm install -g pnpm
  displayName: 'Install pnpm'

# Install the packages
- script: |
    pnpm install
  displayName: 'Install project packages'

# Pre-build checks: lint
- script: |
    pnpm lint
  displayName: 'Pre-build checks: lint'

# Build the project
- script: |
    pnpm build
  displayName: 'Build project'

- task: CopyFiles@2
  displayName: 'Copy Build to Staging Directory'
  inputs:
    Contents: 'dist/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), ne(variables.isPullRequest, true))
