steps:
# Use Node version 18.x
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Use Node.js $(nodeVersion)'

# Use pnpm (much faster)
- script: |
    npm install -g pnpm
  displayName: 'Install pnpm'

# Install the packages
- script: |
    pnpm install
  displayName: 'Install project packages'

# Pre-build checks: lint, test
- script: |
    pnpm lint
  displayName: 'Pre-build checks: lint, test'

# Build the project
- script: |
    pnpm build
  displayName: 'Build project'

- task: CopyFiles@2
  displayName: 'Copy Build Output'
  inputs:
    Contents: 'dist/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    echo $(artifactName)
    echo $(azureSubscription)
  displayName: 'Print the build directory'

- task: PublishBuildArtifacts@1
  displayName: 'Publish to Azure Pipelines'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'www'
  condition: and(succeeded(), ne(variables.isPullRequest, true), or(eq(variables.isDev, true), eq(variables.isProd, true)))

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (a9b787cf-7a6e-4c05-a790-adc3bf941755)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az storage blob upload-batch --destination \$web --account-name "bidportaldemodev" --source "$(Build.ArtifactStagingDirectory)/dist" --overwrite true'
