# Trigger pipeline from branches
trigger:
  branches:
    include:
    - develop
    - main

# Trigger pipeline from PRs
# By default, PR trigger is disabled. See Azure DevOps Project Settings > Triggers > Limit building pull requests from forked GitHub repositories
pr:
  autoCancel: true
  branches:
    include:
      - develop
      - main

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: nodeVersion
    value: '18.x'
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  # Set the library group variable. The group is defined in Azure DevOps.
  - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['System.PullRequest.TargetBranch'], 'develop')) }}:
      - group: bid-portal-demo-dev
  - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['System.PullRequest.TargetBranch'], 'main')) }}:
      - group: bid-portal-demo-prod

stages:
# Build Stage for Dev
- stage: BuildStage
  displayName: 'Build'
  jobs:
  - job: BuildJob
    steps:
    - template: build-steps.yml
# Deployment Stage for Dev
- stage: DeployStage
  displayName: 'Deploy'
  condition: and(succeeded(), ne(variables.isPullRequest, true))
  dependsOn: BuildStage
  jobs:
  - job: DeployJob
    steps:
    - template: deploy-steps.yml
