# Trigger pipeline from branches
trigger:
  branches:
    include:
    - develop

# Trigger pipeline from PRs. Currently, has to be configured in Azure DevOps settings for it to fully work
pr:
  autoCancel: true
  branches:
    include:
      - develop

# Environment to use
pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  isDev: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['System.PullRequest.TargetBranch'], 'develop'))]
  isPullRequest: eq(variables['Build.Reason'], 'PullRequest')

stages:
  - stage: DevStage
    displayName: 'Stage for Dev'
    condition: eq(variables.isDev, true)
    variables:
      - group: bid-portal-demo-dev
      - name: artifactName
        value: artifact-dev
    jobs:
      - job: CommonSteps
        steps:
          - template: common-steps-azure-pipeline.yml
